[package]
name = "PebbleVault-Server"
version = "0.1.0"
edition = "2021"

[dependencies]
PebbleVault = { path = "./PebbleVault" }
colored = "2.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
text_io = "0.1"
